### ISSUE TITLE
Critical Error on Test ArcGIS REST Harvest

### ISSUE THREAD

**Issue by JJediny** [GSA/catalog-app#28]
```
harvester-gather-consumer_1 | 
harvester-gather-consumer_1 | Traceback (most recent call last):
harvester-gather-consumer_1 |   File "/usr/bin/ckan", line 59, in <module>
harvester-gather-consumer_1 |     load_entry_point('PasteScript', 'console_scripts', 'paster')()
harvester-gather-consumer_1 |   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
harvester-gather-consumer_1 |     invoke(command, command_name, options, args[1:])
harvester-gather-consumer_1 |   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
harvester-gather-consumer_1 |     exit_code = runner.run(args)
harvester-gather-consumer_1 |   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
harvester-gather-consumer_1 |     result = self.command()
harvester-gather-consumer_1 |   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 135, in command
harvester-gather-consumer_1 |     gather_callback(consumer, method, header, body)
harvester-gather-consumer_1 |   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/queue.py", line 230, in gather_callback
harvester-gather-consumer_1 |     harvest_object_ids = harvester.gather_stage(job)
harvester-gather-consumer_1 |   File "/usr/lib/ckan/src/ckanext-datajson/ckanext/datajson/harvester_base.py", line 144, in gather_stage
harvester-gather-consumer_1 |     parent_identifier = dataset.get('isPartOf')
harvester-gather-consumer_1 | AttributeError: 'unicode' object has no attribute 'get'
catalogapp_harvester-gather-consumer_1 exited with code 1
```

**Comment by kvuppala** [comment]
@JJediny Can you share the ArcGIS endpoint you were testing, if it is FGDC shema?

**Comment by JJediny** [comment]
@dano-reisys @kvuppala Pick any https://github.com/JJediny/nationalmap/blob/master/datasources/01_ArcGIS_Providers.json

**Comment by dano-reisys** [comment]
I tried to harvest thig ArcGIS (http://usfs.maps.arcgis.com/) endpoint through catalog-app without success.

**Comment by FuhuXia** [comment]
@dano-reisys everything looks fine to me. i just did today with 1493 datasets harvested using catalog-app. What error you got?

**Comment by FuhuXia** [comment]
Harvester is looking at this path `/sharing/search?f=pjson&q=test` when harvesting an arcgis endpoint. None of those listed in the 01_ArcGIS_Providers.json support this api path.
