### ISSUE TITLE
SSL error on harvest from Github Pages hosted data.json file

### ISSUE THREAD

**Issue by JJediny** [GSA/catalog-app#39]
Working on a jekyll based CKAN recent work was done to generate a consildated data.json from individual entries, in testing this data.json endpoint with catalog-app getting a strange SSL error that is causing the `comsumer` container to exit 1, here is the endpoint tested with:
http://demo.jkan.io/data.json

```
harvester-gather-consumer_1 | 2016-04-06 04:42:04,246 DEBUG [ckanext.harvest.queue] Received harvest job id: e18cb46f-bb90-4db2-88b5-5a9da5975282
harvester-gather-consumer_1 | Traceback (most recent call last):
harvester-gather-consumer_1 |   File "/usr/bin/ckan", line 59, in <module>
harvester-gather-consumer_1 | 
harvester-gather-consumer_1 |     load_entry_point('PasteScript', 'console_scripts', 'paster')()
harvester-gather-consumer_1 |   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
harvester-gather-consumer_1 |     invoke(command, command_name, options, args[1:])
harvester-gather-consumer_1 |   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
harvester-gather-consumer_1 |     exit_code = runner.run(args)
harvester-gather-consumer_1 |   File "/usr/lib/ckan/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
harvester-gather-consumer_1 |     result = self.command()
harvester-gather-consumer_1 |   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 135, in command
harvester-gather-consumer_1 |     gather_callback(consumer, method, header, body)
harvester-gather-consumer_1 |   File "/usr/lib/ckan/src/ckanext-harvest/ckanext/harvest/queue.py", line 230, in gather_callback
harvester-gather-consumer_1 |     harvest_object_ids = harvester.gather_stage(job)
harvester-gather-consumer_1 |   File "/usr/lib/ckan/src/ckanext-datajson/ckanext/datajson/harvester_base.py", line 118, in gather_stage
harvester-gather-consumer_1 |     source_datasets, catalog_values = self.load_remote_catalog(harvest_job)
harvester-gather-consumer_1 |   File "/usr/lib/ckan/src/ckanext-datajson/ckanext/datajson/harvester_datajson.py", line 35, in load_remote_catalog
harvester-gather-consumer_1 |     datasets = json.loads(lstrip_bom(urllib2.urlopen(req).read()))
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
harvester-gather-consumer_1 |     return _opener.open(url, data, timeout)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 410, in open
harvester-gather-consumer_1 |     response = meth(req, response)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
harvester-gather-consumer_1 |     'http', request, response, code, msg, hdrs)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 442, in error
harvester-gather-consumer_1 |     result = self._call_chain(*args)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
harvester-gather-consumer_1 |     result = func(*args)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
harvester-gather-consumer_1 |     return self.parent.open(new, timeout=req.timeout)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 404, in open
harvester-gather-consumer_1 |     response = self._open(req, data)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 422, in _open
harvester-gather-consumer_1 |     '_open', req)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
harvester-gather-consumer_1 |     result = func(*args)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
harvester-gather-consumer_1 |     return self.do_open(httplib.HTTPSConnection, req)
harvester-gather-consumer_1 |   File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
harvester-gather-consumer_1 |     raise URLError(err)
harvester-gather-consumer_1 | urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
catalogapp_harvester-gather-consumer_1 exited with code 1
```

**Comment by FuhuXia** [comment]
bumping python to 2.7.10 solved the issue. https://github.com/GSA/catalog-app/commit/5b56839d2cfd9776001c223ac9784fc76338b050
